# Railway configuration for memory and CPU optimization
[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "node --max-old-space-size=220 app.js"
restartPolicyType = "no" # Disable automatic restarts
healthcheckPath = "/health" # Use our simplified health endpoint
healthcheckTimeout = 30
healthcheckInterval = 60

[services.marden-backend-service]
internal_port = 3000
auto_stop = false # Don't auto-stop the service
memory = "256MB"
cpu = 0.3 # Lower to 30% CPU
root_directory = "."
